### ISSUE TITLE
AXStreamer - no reaction on receiving end of the stream.

### ISSUE THREAD

**Issue by lukkas** [Streamaxia/iOS-Open-SDK#12]
I'm currently migrating from AXRecorder to AXStreamer, cause I need a little but more customizability. I couldn't get it to work, so I've tried with your example project, which streams from file and it was the same story. The only thing I've changed, is that I've used an example video file, which I've added to app bundle (and of course the stream key).

This is what happens:
- when I'm calling `startStreaming(completion:)` on AXStreamer, completion never gets called, neither with success, nor error
- I'm getting the status change via delegate though. Then I start feeding `CMSampleBuffer`s to streamer and enable stream source
- I'm getting callback via `AXStreamSourceDelegate`, that source did connect
- there's no reaction on the receiving end of the stream

I've verified that video frames are indeed passed to streamer, however I needed to comment out the code responsible for audio frames, cause it crashes for me. There's already an issue for that, though:
https://github.com/Streamaxia/iOS-Open-SDK/issues/10

**Comment by chelemen-razvan** [comment]
Should be fixed in the latest release

**Comment by lukkas** [comment]
Hi @chelemen-razvan. Are you sure you've committed the right thing?
It's still the same for me. I've cleared my caches, derived data etc, so I guess I'm good on my site. I can see that binaries differ, but behavior hasn't changed.

**Comment by chelemen-razvan** [comment]
yes, does it still crash when sending audio?

**Comment by lukkas** [comment]
yes, it does

**Comment by lukkas** [comment]
@chelemen-razvan I'm sorry, it seems I've mislead you. It was crashing for the video I was using for testing and it was something with  sending audio frames, so I've assumed too quickly that it's the same thing. Now I'm testing with camera feed and it works just fine.

However completion block in `startStreaming` method still isn't called. There's definitely an improvement though, since youtube (I'm testing it there) shows status `Starting`, so it seems it is connected. No actual content shows up, but I'm getting `Failed to encode sample buffer -> [GenericError]`, so there's probably something wrong with the samples I'm passing. Maybe you have some hints?
Anyway, I'll research further and get back to you if I fix it.

**Comment by lukkas** [comment]
@chelemen-razvan I've handled sample encoding error. It was about audio samples and I needed to set number of channels and sample rate in streamer's audio settings. 

I'm still struggling to make the streaming work though. I can see it's connecting, cause I'm getting green bar on youtube (I test it there) and it keeps  saying "STARTING", but no actual video or audio content appears. Any ideas?

**Comment by bunchhaychea** [comment]
Hi @lukkas can you post code snippet on how you fixed the `Failed to encode sample buffer -> [GenericError]` error?
